name: Sync Docker Image to GitHub

on:
  push:
    branches:
      - main   # or the branch where you want to update
  workflow_dispatch: # allows you to trigger manually if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: |
        docker pull premkumar000000007/jenni-react:latest

    - name: Extract changes from Docker image
      run: |
        # Assuming your changes are in a specific directory, copy them
        docker run --rm premkumar000000007/jenni-react:latest /bin/bash -c "cp -r /path/to/changes /workspace/"

    - name: Commit and push changes to GitHub
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Automated update from Docker image"
        git push origin main
