name: Docker Push and GitHub Sync

on:
  push:
    branches:
      - main # The branch where Docker Hub updates the image

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: |
        docker pull yourdockerhubusername/your-image-name:latest

    - name: Copy React app files from Docker container to repo
      run: |
        # Assume your container is running the app
        docker run -d --name react-app yourdockerhubusername/your-image-name:latest
        docker cp react-app:/path/to/your/app /path/in/your/repo
        docker stop react-app

    - name: Commit and push changes to GitHub
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git add .
        git commit -m "Sync React app changes from Docker"
        git push origin main
